### ISSUE TITLE
fix the deployment issues

### ISSUE THREAD

**Issue by redhatdevn16** [redhatdevn16/portfolio#1]
I am trying to deploy this repository to github.io site.
I am using node.js v14.18.1

**Comment by luckydevn16** [comment]
It seems your portfolio has been created by vue.js.
you should first fix all issues while running "npm run build".

**Comment by redhatdevn16** [comment]
> It seems your portfolio has been created by vue.js. you should first fix all issues while running "npm run build".

My portfolio website has been built via vue.js.
I've already fixed the building issues.

**Comment by luckydevn16** [comment]
npm install --save-dev gh-pages

you should put following script on the package.json
"predeploy": "npm run build",
"deploy": "gh-pages -d dist"

**Comment by redhatdevn16** [comment]
great!
it seems the site deployment toolkit is working now.

**Comment by luckydevn16** [comment]
ok.

**Comment by redhatdevn16** [comment]
at the end of deployment, there are some unknown issues.
the deployment failed.

**Comment by luckydevn16** [comment]
oh, you should use node.js v16.x.
please try with it.

**Comment by redhatdevn16** [comment]
it's working now.
it has been deployed successfully.

**Comment by luckydevn16** [comment]
please put following script in package.json.
"predeploy": "npm run build",
"deploy": "gh-pages -d dist"
